[package]
name = "crypto_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
age = "0.9.2"
anyhow = "1.0.75"
dirs = "5.0.1"
rand = "0.8.5"
hmac-sha512 = "1.1.5"
fltk = "1.4.13"
camino = "1.1.6"
fltk-theme = "0.7.1"
thiserror = "1.0.49"
flate2 = "1.0.27"
tar = "0.4.40"


# optimize for size
[profile.release]
strip = true
lto = true
opt-level = "z"
debug = 0
overflow-checks = false
panic = "abort"
codegen-units = 1
