[package]
name = "crypto-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
age = "0.9.2"
anyhow = "1.0.71"
camino = "1.1.4"
constant_time_eq = "0.3.0"
dirs = "5.0.1"
hmac-sha512 = "1.1.5"
# latest inquire release has a password confirmation bug
# inquire = "0.6.2"
inquire = { git = "https://github.com/mikaelmello/inquire", rev = "3efb148c5cb6523d9cfb1cd07a0d8c093b9ed165" }
owo-colors = "3.5.0"
rand = "0.8.5"
regex = "1.8.4"


# optimize for size
[profile.release]
strip = true
lto = true
opt-level = "z"
debug = 0
overflow-checks = false
panic = "abort"
codegen-units = 1
