[package]
name = "crypto_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
age = "0.9.2"
anyhow = "1.0.71"
dirs = "5.0.1"
rand = "0.8.5"
hmac-sha512 = "1.1.5"
fltk = { version = "1.4.7", features = ["fltk-bundled"] }
camino = "1.1.4"
fltk-theme = "0.7.1"
thiserror = "1.0.41"


# optimize for size
[profile.release]
strip = true
lto = true
opt-level = "z"
debug = 0
overflow-checks = false
panic = "abort"
codegen-units = 1
