[package]
name = "crypto-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
age = "0.9.2"
anyhow = "1.0.71"
dirs = "5.0.1"
owo-colors = "3.5.0"
rand = "0.8.5"
spinoff = { version = "0.7.0", features = ["dots"] }
clap = { version = "4.3.4", features = ["derive"] }


# optimize for size
[profile.release]
strip = true
lto = true
opt-level = "z"
debug = 0
overflow-checks = false
panic = "abort"
codegen-units = 1